## NumPy

In [1]:
import numpy as np

In [3]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

## Numpy Arrays(ndarray)

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [12]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=complex)

In [14]:
matrix

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [13]:
type(matrix[0][0])

numpy.complex128

In [20]:
ndarray = np.array([1, 2, 3], dtype=np.float32)

In [19]:
ndarray.astype(np.float64)

array([1., 2., 3.])

In [22]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [23]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
array1 / array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array3 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

In [36]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [37]:
array2 + array3

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [38]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ndarray + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
ndarray = np.array([[1,2], [3,4], [5,6]])

In [46]:
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
ndarray.shape

(3, 2)

In [48]:
ndarray.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])

In [55]:
ndarray1.shape

(3,)

In [56]:
ndarray2.shape

(1, 3)

In [59]:
expand_ndarray = np.expand_dims(ndarray1, axis=1)

In [61]:
expand_ndarray.shape

(3, 1)

In [62]:
np.squeeze(expand_ndarray)

array([1, 2, 3])

In [63]:
expand_ndarray

array([[1],
       [2],
       [3]])

In [64]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [65]:
ndarray.shape

(3, 3)

In [67]:
ndarray.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
ndarray = np.array([1,2,3,4])

In [69]:
ndarray[0]

1

In [70]:
ndarray[-1]

4

In [71]:
ndarray = np.array([[1,2], [3,4], [5,6]])

In [72]:
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
ndarray[0, 1]

2

In [76]:
ndarray = np.array([1, 2, 3, 4])

In [77]:
ndarray[1:3]

array([2, 3])

In [78]:
ndarray[:3]

array([1, 2, 3])

In [79]:
ndarray[1:]

array([2, 3, 4])

In [81]:
ndarray[-2]

3

In [82]:
ndarray[-2:]

array([3, 4])

In [83]:
ndarray[:]

array([1, 2, 3, 4])

In [84]:
ndarray = np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12],[13,14,15,16]])

In [88]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [85]:
ndarray.shape

(4, 4)

In [86]:
ndarray[:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
ndarray[:3, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [90]:
ndarray[:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [100]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [97]:
list(range(2, 15, 4))

[2, 6, 10, 14]

In [103]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [105]:
np.logspace(0, 3, 10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [106]:
np.linspace(0, 3, 10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [107]:
np.linspace(0, 3, 10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [108]:
10 ** 0.3333

2.1542693374042363

In [110]:
shape = (3, 4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [111]:
np.zeros(3)

array([0., 0., 0.])

In [112]:
np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [113]:
np.ones(3)

array([1., 1., 1.])

In [116]:
np.ones((5,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [119]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [121]:
np.eye(3, 10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [134]:
# 疑似乱数　pseudo random
np.random.rand(3, 4, 5)

array([[[0.66873277, 0.47688233, 0.01313636, 0.35300609, 0.4920718 ],
        [0.73009121, 0.46862834, 0.45740492, 0.13766274, 0.01088873],
        [0.75827826, 0.31995284, 0.98438345, 0.22023423, 0.33870803],
        [0.52389614, 0.75489146, 0.46385778, 0.12482254, 0.31250138]],

       [[0.50451917, 0.67384901, 0.77014996, 0.13033578, 0.02291513],
        [0.51908232, 0.80998871, 0.01260377, 0.67246984, 0.68680823],
        [0.44924675, 0.91478869, 0.64436108, 0.00523984, 0.48442845],
        [0.85931781, 0.83039957, 0.6491542 , 0.67369842, 0.57849958]],

       [[0.27411978, 0.56052999, 0.67172978, 0.35242963, 0.85582837],
        [0.19503749, 0.74732081, 0.28960275, 0.77379929, 0.42773733],
        [0.80769841, 0.35353486, 0.21369324, 0.76728451, 0.30864195],
        [0.73324507, 0.74447315, 0.2213967 , 0.21411214, 0.19894792]]])

In [127]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [128]:
np.random.rand()

0.7203244934421581

## np.random.randn()

In [133]:
np.random.randn(10, 10, 3)

array([[[ 3.26145467e-02, -1.37311732e+00,  3.15159392e-01],
        [ 8.46160648e-01, -8.59515941e-01,  3.50545979e-01],
        [-1.31228341e+00, -3.86955093e-02, -1.61577235e+00],
        [ 1.12141771e+00,  4.08900538e-01, -2.46169559e-02],
        [-7.75161619e-01,  1.27375593e+00,  1.96710175e+00],
        [-1.85798186e+00,  1.23616403e+00,  1.62765075e+00],
        [ 3.38011697e-01, -1.19926803e+00,  8.63345318e-01],
        [-1.80920302e-01, -6.03920628e-01, -1.23005814e+00],
        [ 5.50537496e-01,  7.92806866e-01, -6.23530730e-01],
        [ 5.20576337e-01, -1.14434139e+00,  8.01861032e-01]],

       [[ 4.65672984e-02, -1.86569772e-01, -1.01745873e-01],
        [ 8.68886157e-01,  7.50411640e-01,  5.29465324e-01],
        [ 1.37701210e-01,  7.78211279e-02,  6.18380262e-01],
        [ 2.32494559e-01,  6.82551407e-01, -3.10116774e-01],
        [-2.43483776e+00,  1.03882460e+00,  2.18697965e+00],
        [ 4.41364444e-01, -1.00155233e-01, -1.36444744e-01],
        [-1.19054188e-

In [136]:
np.random.normal(10, 1)

9.656099290789607

## np.random.randint

In [138]:
np.random.randint(10, 100, (2, 3) )

array([[93, 37, 66],
       [18, 65, 86]])

In [141]:
np.random.randint(10)

7

## np.random.choice()

In [145]:
a = [1, 2, 3]
np.random.choice(a)

3

In [146]:
index_pool = np.arange(0, 10 , 2)
index_pool

array([0, 2, 4, 6, 8])

In [148]:
idx = np.random.choice(index_pool)

In [149]:
ndarray[idx]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [150]:
_

4

In [164]:
std_norm = np.random.randn(5, 5)
std_norm

array([[ 0.42197406, -1.78806631, -0.32311629, -0.50802808,  0.02615007],
       [ 0.90937162,  1.09142168, -0.58258537,  0.2256999 ,  0.63147683],
       [ 0.35072515,  0.71196516, -1.20766757, -0.28960698, -2.18548992],
       [ 1.33835709,  0.18775318,  0.77853874, -0.60484893, -1.02667242],
       [ 0.10604959,  0.40973852,  0.97041677, -0.04208739, -0.51910518]])

In [153]:
std_norm.max()

2.4546728495677974

In [154]:
np.max(std_norm)

2.4546728495677974

In [155]:
std_norm.min()

-2.047910499482044

In [156]:
std_norm.argmax()

16

In [158]:
std_norm.argmin()

21

In [160]:
std_norm.flatten()[16]

2.4546728495677974

In [165]:
std_norm.mean()

-0.036705443855586696

In [166]:
# 中央値
np.median(std_norm)

0.10604959269537204

In [179]:
#中央値　VS　平均値
import time
a = np.random.randn(1000,1000)
before = time.time()
np.median(a)
after_median = time.time()
np.mean(a)
after_mean = time.time()
print("median took {} sec".format(after_median - before))
print("mean took {} sec".format(after_mean - after_median))

median took 0.01140451431274414 sec
mean took 0.0007517337799072266 sec


In [171]:
np.mean(a)

-0.0004153335742462984

In [172]:
time.time()

1651412334.810134

In [180]:
# 標準偏差
np.std(std_norm)

0.8649893637005204

In [184]:
std_norm.max(axis=1)

array([0.42197406, 1.09142168, 0.71196516, 1.33835709, 0.97041677])

In [185]:
#平方根 square root
np.sqrt([1,2,3,4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [192]:
x = np.linspace(1, 10, 10)
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [189]:
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [196]:
# 指数関数　Exponetial function
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [197]:
np.e

2.718281828459045

In [198]:
# 合計
# 合計　（summation）
np.sum([1, 2, 3])

6

In [199]:
array = np.arange(1, 11)

In [200]:
np.sum(array)

55

In [202]:
ndarray = array.reshape(2, 5)

In [204]:
np.sum(ndarray, axis=1)

array([15, 40])

In [207]:
#絶対値
array = np.arange(-10, 0)
array

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [211]:
np.average(array)

-5.5

In [210]:
np.log(4)

1.3862943611198906

In [212]:
# Nan : Not a Number

In [213]:
np.log(-100)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


nan

In [214]:
np.nan

nan

In [215]:
type(np.nan)

float

In [218]:
a = None
a is None

True

In [222]:
np.isnan(np.log(-100))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


True

In [224]:
np.log(-100) == np.nan

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


False

## その他便利関数

In [226]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [227]:
np.clip(array, 4, 6)

array([4, 4, 4, 4, 4, 5, 6, 6, 6, 6])

In [228]:
1e-4

0.0001

## numpy.arrayのcondition

In [229]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## mp.whare

In [233]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [240]:
result, = np.where(array > 3)

In [241]:
result

array([4, 5, 6, 7, 8, 9])

In [236]:
#filter
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [239]:
array[array > 3]

array([4, 5, 6, 7, 8, 9])

In [243]:
ndarray = array.reshape(2, 5)
ndarray[ndarray>3] # flattenされる

array([4, 5, 6, 7, 8, 9])

In [251]:
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [248]:
(ndarray >= 0).all()

True

In [249]:
(ndarray > 3).any()

True

In [252]:
(ndarray > 3).all(axis= 1)

array([False,  True])

## np.unique

In [253]:
array = np.array([1, 1, 2, 3, 4, 2, 3, 4, 5])
array

array([1, 1, 2, 3, 4, 2, 3, 4, 5])

In [254]:
np.unique(array)

array([1, 2, 3, 4, 5])

In [255]:
np.unique(array, return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 1]))

## np.bincount()

In [256]:
np.bincount(array)

array([0, 2, 2, 2, 2, 1])

In [259]:
ndarray_even = np.arange(0, 18, 2).reshape(3, 3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [261]:
ndarray_odd = np.arange(1, 19, 2).reshape(3,3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [263]:
np.concatenate([ndarray_even, ndarray_odd], axis=1)

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

In [270]:
np.stack([ndarray_even, ndarray_odd], axis=0)

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [284]:
np.stack([ndarray_even, ndarray_odd], axis=-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [285]:
stacked_array = _

In [286]:
stacked_array.shape

(3, 3, 2)

In [287]:
ndarray = np.random.randn(3, 4)

In [288]:
ndarray

array([[-0.03181186, -0.53108136,  0.27782378,  0.35656948],
       [ 1.24037855,  0.13090599,  0.2203359 , -0.52268188],
       [-0.75111327,  1.39688242, -0.20556777,  0.04749593]])

In [289]:
ndarray.shape

(3, 4)

In [290]:
np.transpose(ndarray)

array([[-0.03181186,  1.24037855, -0.75111327],
       [-0.53108136,  0.13090599,  1.39688242],
       [ 0.27782378,  0.2203359 , -0.20556777],
       [ 0.35656948, -0.52268188,  0.04749593]])

In [291]:
transpose_ndarray = _

In [292]:
transpose_ndarray.shape

(4, 3)

In [293]:
ndarray.T

array([[-0.03181186,  1.24037855, -0.75111327],
       [-0.53108136,  0.13090599,  1.39688242],
       [ 0.27782378,  0.2203359 , -0.20556777],
       [ 0.35656948, -0.52268188,  0.04749593]])

In [294]:
ndarray = np.random.randn(3, 4, 5)
ndarray.T.shape

(5, 4, 3)

In [296]:
ndarray.T

array([[[ 1.21485749,  0.60895776, -0.49410865],
        [-0.51581476,  0.44203138,  0.96103666],
        [-0.40000511, -0.22559046,  0.87667159],
        [-0.5233708 ,  1.46449328,  0.95872332]],

       [[ 0.67772869, -0.63856392, -1.12070207],
        [-0.56753567, -1.49767736,  0.07184954],
        [ 1.57693769, -0.27588333, -1.15520484],
        [ 1.78196346,  0.23834617, -2.67590009]],

       [[-2.59127401,  1.25463139,  0.6957711 ],
        [-0.16808786,  0.37866907, -1.54461797],
        [ 1.30486333, -0.51449571, -1.28963989],
        [ 0.15924662,  0.58019065,  1.21805134]],

       [[-1.30065448,  0.73927372,  0.2783835 ],
        [-1.12282864,  0.01375357,  0.88122989],
        [-0.50118466,  1.61558971,  0.61572278],
        [-1.60511131,  0.99409542, -0.40716118]],

       [[-0.29046384, -1.47660685,  1.46084633],
        [ 1.97766395,  0.67586391, -0.82348666],
        [ 1.22991317,  0.9497154 , -0.38402709],
        [ 1.0002179 ,  0.42870278,  0.25718821]]])

In [297]:
ndarray = np.random.rand(3, 4, 5)
ndarray.shape

(3, 4, 5)

In [298]:
np.save("sample_ndarray",ndarray)

In [303]:
loaded_ndarray = np.load("sample_ndarray.npy")
loaded_ndarray.shape

(3, 4, 5)

In [304]:
dictionary = {
    "id": 123456,
    "image": ndarray
}

In [305]:
np.save("sample_dict", dictionary)

In [313]:
loaded_dict = np.load("sample_dict.npy", allow_pickle=True)[()]

In [314]:
loaded_dict

{'id': 123456,
 'image': array([[[0.59668498, 0.3054255 , 0.62379672, 0.69462809, 0.14055338],
         [0.72397249, 0.08081015, 0.50076249, 0.98498111, 0.59521219],
         [0.18860118, 0.50796282, 0.42620212, 0.24227939, 0.7349522 ],
         [0.44558757, 0.73125875, 0.24684032, 0.45108509, 0.00119267]],
 
        [[0.14282221, 0.97010407, 0.45479344, 0.96845817, 0.84954203],
         [0.36198631, 0.08709296, 0.39504515, 0.33680035, 0.27303847],
         [0.7982224 , 0.68703966, 0.34494327, 0.33749213, 0.99129477],
         [0.17531442, 0.68506254, 0.04489634, 0.2444237 , 0.8960885 ]],
 
        [[0.76799758, 0.55509565, 0.82541068, 0.89177847, 0.22360179],
         [0.17514982, 0.74841404, 0.01311353, 0.09623394, 0.51651479],
         [0.5309474 , 0.57633209, 0.30874432, 0.07815101, 0.61294959],
         [0.21666623, 0.91807963, 0.93376569, 0.90165661, 0.52477719]]])}

In [312]:
a = np.array({"a": 1})
a[()]

{'a': 1}